Analyzing the dependencies
eclipse-cognicrypt/CogniCrypt pull request #309
Opened 2019-08-07 14:02 UTC by shahrzadav

# Description

New context menu button for analyzing dependencies of project added, also added one more option in preference page for including dependencies while analyzing the project.

Fixes #190

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

It has been tested in eclipse runtime with maven and non maven projects.

**Test Configuration**:
* Eclipse Version: 2018-12 (4.10.0)
* Java Version: 1.8
* OS: Windows 10

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2019-08-10 15:19 UTC, kruegers requested changes
Thanks for the pull request. Before I review it, please cleanup your source files first.  
1) Methods should start with a lowercase letters.
2) Comented code should either be removed or uncommented (depending on whether it is needed or not.)
3) Implement the usual error logging through the Activator class and a meanigful error message.

2019-08-19 08:58 UTC, shahrzadav commented
@kruegers sorry for delay, would you check please? I made a few changes as you requested

2019-09-09 12:48 UTC, kruegers requested changes

2019-09-09 12:48 UTC, kruegers commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/handlers/RunAnalysisHandler.java
> +					if (answr == JOptionPane.NO_OPTION) {
Superfluous.

2019-09-09 12:48 UTC, kruegers commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/handlers/RunAnalysisHandler.java
> +				// TODO Auto-generated catch block
Please implement appropriate exception handling here.

2019-09-09 12:48 UTC, kruegers commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/handlers/RunAnalysisHandler.java
> +	public static int saveFile(IFile openFileInEditor) throws Exception {
This should not be part of this PR, should it? Please use branches when working on separate issues.

2019-09-09 12:48 UTC, kruegers commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/results/ResultsCCUIListener.java
> +		if (this.depVariable) {
Please move this block to first line of this method.

2019-09-09 12:48 UTC, kruegers commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/sootbridge/SootRunner.java
> +			if (store.getBoolean(Constants.ANALYSE_DEPENDENCIES) == true || dependencyAnalyser == true) {
Don't make statements longer than necessary:
a == true <==> a

2019-09-10 13:07 UTC, closed without merging