suppress errors related to legacy client in code generator
eclipse-cognicrypt/CogniCrypt pull request #400
Opened 2020-06-29 07:55 UTC by shahrzadav

Signed-off-by: Shahrzad <shahrzad.asghari73@gmail.com>

# Description

When the user selects Legacy client in code generator in secure communication task, errors related to this constraint will be suppressed, if and only if the checkbox related to this in preference page is also selected.

Fixes # (193)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

It has been tested in runtime.

**Test Configuration**:
* Eclipse Version: Eclipse Version: 2019-09 R (4.13.0)
* Java Version: 1.8
* OS: Windows 10

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-07-09 10:15 UTC, AnakinRaW requested changes

2020-07-09 10:15 UTC, AnakinSklavenwalker commented on plugins/de.cognicrypt.codegenerator/src/main/java/de/cognicrypt/codegenerator/wizard/Configuration.java
> +	public Configuration(Map<?, ?> constraints, String pathOnDisk, String taskName) throws IOException {
what would happen if an IOException was thrown? Will the feature not work at all or would it be able to work regardless?

If it still would work, please catch the exception, log it and then forget it.

2020-07-09 10:15 UTC, AnakinSklavenwalker commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/results/ResultsCCUIListener.java
> +			if (prefStore.getBoolean(Constants.SUPPRESS_LEGACYCLIENT_ERRORS) && conError.getBrokenConstraint().toString().equals("VC:protocol - TLSv1.2,") && isLegacyClient()) {
For extensibility reasons: please put the `"VC:protocol - TLSv1.2,"` string into some class that holds this as an constant.

2020-07-09 10:15 UTC, AnakinSklavenwalker commented on plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/results/ResultsCCUIListener.java
> +					String clientsQuestion = "Which clients should the server at least support?";
please use string constants here that get used for this code and the JSON creation.

2021-09-20 11:57 UTC, shahrzadav commented
@schlichtig, could you please rebuild it?

2021-10-01 10:55 UTC, shahrzadav commented
Made another PR and it is already merged. [https://github.com/eclipse-cognicrypt/CogniCrypt/pull/446](url)

2021-10-01 10:55 UTC, closed without merging